# 1. Member 단일 조회
GET {{host}}/api/members/1
Content-Type: application/json

###

# 2. Member 생성
POST {{host}}/api/members
Content-Type: application/json

{
  "email": "eee@gmail.com",
  "name": "eee"
}

###

# 3. Member 수정
PUT {{host}}/api/members/1
Content-Type: application/json

{
  "name": "new-aaa"
}

###

# 4. Member 페이징 조회
GET {{host}}/api/members/?page=0&size=1
Content-Type: application/json

###